repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.3
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.406
    hooks:
      - id: pyright
        args: [-p, pyrightconfig.json]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: check-merge-conflict

  - repo: local
    hooks:
      - id: pytest-quick
        name: pytest quick (incremental smoke)
        entry: bash -lc 'just test'
        language: system
        stages: [pre-push]
      - id: block-wandb-api-key
        name: Block committing WANDB_API_KEY
        entry: bash -lc 'if git diff --cached -U0 | rg -n "^\\+.*WANDB_API_KEY" -S >/dev/null; then echo "Blocked: WANDB_API_KEY detected in staged changes" >&2; exit 1; fi'
        language: system
        stages: [pre-commit, pre-push]
