repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.3
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.406
    hooks:
      - id: pyright
        args: [-p, pyrightconfig.json]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: check-merge-conflict

  - repo: local
    hooks:
      - id: pytest-quick
        name: pytest quick (FAST=1)
        entry: bash -lc 'FAST=1 JAX_DISABLE_JIT=true JAX_PLATFORM_NAME=cpu XLA_PYTHON_CLIENT_PREALLOCATE=false uv run pytest --testmon -q -ra -n auto --maxfail=1'
        language: system
        stages: [pre-push]
