# Central list of policy waivers. CI fails on expired waivers.
# Format: repeated [[waiver]] tables. Dates use ISO YYYY-MM-DD.

# Example (remove after copying and editing):
# [[waiver]]
# id = "docstring-rollout-symplectic"
# summary = "Allow non-Google docstrings while converting symplectic module"
# owner = "@maintainer"
# scope = "src/viterbo/symplectic/"
# created = "2025-10-02"
# expires = "2025-10-16"
# justification = "Incremental conversion to Google style to keep PRs small"
# removal_plan = "Convert remaining docstrings; remove waiver when Ruff passes"

[[waiver]]
id = "exp1-docstrings-incubation"
summary = "Relax docstring requirements for experimental exp1 modules during incubation"
owner = "@maintainer"
scope = "src/viterbo/exp1/**"
created = "2025-10-09"
expires = "2025-10-23"
justification = "Fast iteration on algorithm design; docstrings focus on semantics and will be added before promotion to stable namespace"
removal_plan = "Add concise Google-style docstrings to exported symbols in exp1 and remove the per-file ignore + waiver"

[[waiver]]
id = "pyright-exp1-temporary-exclude"
summary = "Temporarily exclude experimental exp1 from Pyright to unblock modern implementation"
owner = "@maintainer"
scope = "src/viterbo/exp1/**"
created = "2025-10-11"
expires = "2025-10-25"
justification = "exp1 contains in-progress prototypes that currently fail Pyright; we exclude it briefly so modern module work can proceed through green typecheck gates"
removal_plan = "Resolve exp1 call-issues or promote stable pieces into modern; remove exclusion and this waiver once Pyright passes"
