"""Geometry primitives and polytope helpers."""

from .halfspaces import enumerate_vertices, remove_redundant_facets
from .polytopes import (
    NormalCone,
    Polytope,
    PolytopeCombinatorics,
    affine_transform,
    cartesian_product,
    catalog,
    cross_polytope,
    haim_kislev_action,
    halfspaces_from_vertices,
    hypercube,
    mirror_polytope,
    polytope_combinatorics,
    polytope_fingerprint,
    random_affine_map,
    random_polytope,
    random_transformations,
    regular_polygon_product,
    rotate_polytope,
    simplex_with_uniform_weights,
    translate_polytope,
    truncated_simplex_four_dim,
    vertices_from_halfspaces,
    viterbo_counterexample,
)
from .volume import polytope_volume_fast, polytope_volume_reference

__all__ = [
    "NormalCone",
    "Polytope",
    "PolytopeCombinatorics",
    "affine_transform",
    "cartesian_product",
    "catalog",
    "cross_polytope",
    "enumerate_vertices",
    "haim_kislev_action",
    "halfspaces_from_vertices",
    "hypercube",
    "mirror_polytope",
    "polytope_combinatorics",
    "polytope_fingerprint",
    "polytope_volume_fast",
    "polytope_volume_reference",
    "random_affine_map",
    "random_polytope",
    "random_transformations",
    "regular_polygon_product",
    "remove_redundant_facets",
    "rotate_polytope",
    "simplex_with_uniform_weights",
    "translate_polytope",
    "truncated_simplex_four_dim",
    "vertices_from_halfspaces",
    "viterbo_counterexample",
]
